### PR TITLE
Recommend absolute compiler paths.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by nelhage** [comment]
Want to include a brief note about the rationale? Happy to merge either way.

**Comment by jpeach** [comment]
> Want to include a brief note about the rationale? Happy to merge either way.

Yup good point. Fixed!

**Comment by nelhage** [comment]
Did you push the change? I'm not seeing it.

**Comment by jpeach** [comment]
> Did you push the change? I'm not seeing it.

Ugh, I forgot how to git! Pushed now :)

**Pull request merged**
